### PR TITLE
Fix PreparedQueryClient

### PR DESCRIPTION
**Pull request by dmitriyGarden**
Fixed PreparedQueryClient::create and PreparedQueryClient::execute methods

### CODE REVIEW

**Comment by dcarbone** [comment]
Awesome, thanks for the fix!

**Comment by dmitriyGarden** [comment]
No problem. But we need a new release with fixes.

**Comment by dcarbone** [comment]
indeed, and done.

**Comment by dmitriyGarden** [comment]
Thanks a lot

**Pull request merged**
